language: dart

sudo: false

dart:
  - dev

dart_task:
  - test: --platform vm

cache:
  directories:
    - $HOME/.pub-cache

before_script:
  - pub run bin/check_formatting.dart

script:
  - pub run bin/presubmit.dart
